version: '3.4'

services:
  sharedexpenses:
    image: sharedexpenses
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
